name: Semantic release
description: Release a project using the Semantic Release tool

inputs:
  additional-plugins:
    description: 'Additional Semantic Release plugins to install'
    required: false
  github-token:
    description: 'Token for authenticating to GitHub'
    required: true
  release-config:
    description: 'Sharable Semantic Release configuration to use. If not provided, it is assumed a valid release config is defined locally'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Generate releaserc
      if: ${{ inputs.release-config != '' }}
      shell: bash
      run: |
        cat <<EOF > .releaserc.json
        {
          "extends": "${{ inputs.release-config }}"
        }
        EOF
    - name: Release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GIT_AUTHOR_NAME: k-seth-releaser
        GIT_AUTHOR_EMAIL: 219573145+k-seth-releaser@users.noreply.github.com
        GIT_COMMITTER_NAME: k-seth-releaser
        GIT_COMMITTER_EMAIL: 219573145+k-seth-releaser@users.noreply.github.com
      run: |
        npm install --no-save semantic-release ${{ inputs.release-config }} ${{ inputs.additional-plugins }}
        npx --no semantic-release
