name: Setup Node.js
description: same as actions/setup-node but with versioning in a single place.

inputs:
  cache:
    description: 'Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm'
    required: false
  node-version:
    description: 'Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0'
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}
