name: Validate Maven
description: Build and verify a Maven-based project

inputs:
  additional-profiles:
    description: 'Comma-separated string of additional profiles to set when running tests'
    required: false

runs:
  using: composite
  steps:
    - name: Build and test
      shell: bash
      run: |
        PROFILES=coverage
        if [[ -n "${{ inputs.additional-profiles }}" ]]; then
          PROFILES+=,${{ inputs.additional-profiles }}
        fi

        mvn -B -fae -Dmaven.source.skip=true clean verify -P "${PROFILES}"
