name: Eslint

on:
  workflow_call:
    inputs:
      node-version:
        description: 'The Node.js version to use.'
        required: true
        type: string

jobs:
  lint:
    name: Eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # 4.4.0
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: npx eslint .
