name: Eslint

on:
  workflow_call:
    inputs:
      node-version:
        description: 'The Node.js version to use.'
        required: true
        type: string

jobs:
  lint:
    name: Eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: npx eslint .
