name: Release Maven project

on:
  workflow_call:
    inputs:
      java-version:
        description: 'The Java version to set up.'
        required: false
        type: string
      private-maven-proxy-repository:
        description: 'Full URL of the private Maven repository to use'
        required: true
        type: string
      private-maven-user:
        description: 'User to authenticate to the private Maven repository with'
        required: true
        type: string
      private-npm-registry:
        description: 'Full URL of the private NPM registry to use'
        required: true
        type: string
      private-server-base:
        description: 'Base url for pointing to private Maven repositories'
        required: true
        type: string
    secrets:
      github-token:
        description: 'Token for authenticating to GitHub'
        required: true
      private-maven-token:
        description: 'Token for authenticating to the private Maven repository'
        required: true
      private-npm-token:
        description: 'Token for authenticating to the private NPM registry'
        required: true

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: Th3-Hero/github-workflows-and-actions/checkout@main
      - name: Setup Java
        uses: Th3-Hero/github-workflows-and-actions/setup-java@main
        with:
          cache: 'maven'
          java-version: ${{ inputs.java-version }}
          private-maven-proxy-repository: ${{ inputs.private-maven-proxy-repository }}
          private-maven-token: ${{ secrets.private-maven-token }}
          private-maven-user: ${{ inputs.private-maven-user }}
          private-server-base: ${{ inputs.private-server-base }}
      - name: Setup Node
        uses: Th3-Hero/github-workflows-and-actions/setup-node@main
        with:
          node-version: 'lts/*'
          private-npm-registry: ${{ inputs.private-npm-registry }}
          private-npm-token: ${{ secrets.private-npm-token }}
          scope: '@th3-hero'
      - name: Release
        uses: Th3-Hero/github-workflows-and-actions/semantic-release@main
        with:
          github-token: ${{ secrets.github-token }}
          release-config: '@th3-hero/semantic-release-maven'
