name: Node Validate

on:
  workflow_call:
    inputs:
      node-version:
        description: 'The Node.js version to use.'
        required: true
        type: string
      env-json:
        required: false
        type: string

jobs:
  validate:
    name: Validate Node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # 4.4.0
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Set environment variables
        if: ${{ inputs.env-json != '' }}
        shell: bash
        run: |
          echo '${{ inputs.env-json }}' > env.json
          jq -r 'to_entries | map("\(.key)=\(.value)") | .[]' env.json > .env

      - name: Install dependencies
        run: yarn install

      - name: Build Project
        run: npm run build

      - name: Run Unit tests
        run: npm run test
