name: Node Validate

on:
  workflow_call:
    inputs:
      node-version:
        description: 'The Node.js version to use.'
        required: true
        type: string
      env-json:
        required: false
        type: string

jobs:
  validate:
    name: Validate Node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Set environment variables
        if: ${{ inputs.env-json != '' }}
        shell: bash
        run: |
          echo '${{ inputs.env-json }}' > env.json
          jq -r 'to_entries | map("\(.key)=\(.value)") | .[]' env.json > .env

      - name: Install dependencies
        run: yarn install

      - name: Build Project
        run: npm run build

      - name: Run Unit tests
        run: npm run test
